# Generated by Django 4.0.2 on 2022-03-26 15:48

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_choice_order_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'Choice'), (2, 'Text'), (3, 'Decimal')]),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='step',
            field=models.FloatField(null=True, validators=[api.validators.GreaterThanValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='type',
            field=models.IntegerField(choices=[(1, 'Enumerate'), (2, 'Slider'), (3, 'Field')]),
        ),
    ]
