# Generated by Django 4.0.2 on 2022-03-26 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_value_type_alter_rangequestion_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='max_answers',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
