# Generated by Django 4.0.2 on 2022-03-26 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_multiplechoicequestion_max_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='min_answers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
