# Generated by Django 4.0.2 on 2022-03-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_specialid_alter_respondent_special_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='special_id',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='submit_timestamp',
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SpecialId',
        ),
        migrations.AddField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.respondent'),
        ),
    ]
