# Generated by Django 4.0.2 on 2022-03-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_response_remove_respondent_special_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='respondent',
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.response'),
            preserve_default=False,
        ),
    ]
