# Generated by Django 4.0.2 on 2022-03-29 11:14

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_answer_respondent_answer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangequestion',
            name='step',
            field=models.IntegerField(null=True, validators=[api.validators.GreaterThanValidator(0)]),
        ),
    ]
