# Generated by Django 4.0.2 on 2022-03-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_rangequestion_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openanswer',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rangeanswer',
            name='num',
            field=models.FloatField(null=True),
        ),
    ]
