# Generated by Django 4.0.2 on 2022-03-29 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_openanswer_text_alter_rangeanswer_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openquestion',
            name='max_length',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='min_length',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
