# Generated by Django 4.0.2 on 2022-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_openquestion_max_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangequestion',
            name='type',
            field=models.IntegerField(choices=[(1, 'Enumerate'), (2, 'Slider'), (3, 'Field'), (4, 'Rating')]),
        ),
    ]
