# Generated by Django 4.0.2 on 2022-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_rangequestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangequestion',
            name='type',
            field=models.IntegerField(choices=[(1, 'Enumerate'), (2, 'Slider'), (3, 'Field'), (4, 'Star rating'), (5, 'Smiley rating')]),
        ),
    ]
