# Generated by Django 4.0.2 on 2022-03-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_rangequestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='skip_to_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section'),
        ),
    ]
