# Generated by Django 4.0.2 on 2022-03-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_choice_skip_to_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
