# Generated by Django 4.0.2 on 2022-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_questionnaire_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
