# Generated by Django 4.0.2 on 2022-04-05 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_questionnaire_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='order_num',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='order_num',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='order_num',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
