# Generated by Django 4.0.2 on 2022-04-05 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_choice_order_num_alter_question_order_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='choice',
            name='order_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='order_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='order_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'order_num'], name='api_choice_questio_2ea73d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'order_num'], name='api_questio_section_665439_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['qnaire', 'order_num'], name='api_section_qnaire__824396_idx'),
        ),
    ]
