# Generated by Django 4.0.2 on 2022-04-08 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_question_options_alter_choice_order_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='min_answers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='max',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='min',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='type',
            field=models.IntegerField(choices=[(1, 'Enumerate'), (2, 'Slider'), (3, 'Field'), (4, 'Star rating'), (5, 'Smiley rating')], default=2),
        ),
    ]
