# Generated by Django 4.0.2 on 2022-04-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_multiplechoicequestion_min_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.response'),
        ),
    ]
