# Generated by Django 4.0.2 on 2022-04-11 13:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_answer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=api.models.NON_POLYMORPHIC_CASCADE, to='api.response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=api.models.NON_POLYMORPHIC_CASCADE, to='api.section'),
        ),
    ]
