# Generated by Django 4.0.2 on 2022-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_answer_response_alter_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
