# Generated by Django 4.0.4 on 2022-04-16 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_questionnaire_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='max_answers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='min_answers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
